#!/usr/bin/env node
/**
 * Migrates back/.env to infra/.env for Docker Compose.
 * Reads values from back/.env, generates missing secrets,
 * writes infra/.env. Zero stdout — output goes to file only.
 *
 * Usage: node infra/scripts/migrate-env.mjs
 */

import { randomBytes } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..", "..");
const BACK_ENV = resolve(ROOT, "back", ".env");
const INFRA_ENV = resolve(ROOT, "infra", ".env");

// ── Read back/.env ──────────────────────────────────────────────
const raw = readFileSync(BACK_ENV, "utf8");
const env = {};
for (const line of raw.split("\n")) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith("#")) continue;
  const idx = trimmed.indexOf("=");
  if (idx <= 0) continue;
  const k = trimmed.slice(0, idx).trim();
  const v = trimmed.slice(idx + 1).trim();
  env[k] = v;
}

// ── Generate new values ─────────────────────────────────────────
function genSecret(len = 48) {
  return randomBytes(len).toString("base64").replace(/[+/=]/g, "").slice(0, len);
}

const NEW_DB_PASS = "LT39iKW0nPeXRO48UMdjKbL5fcBbH9";
const NEW_JWT    = genSecret(48);
const NEW_AUTH   = genSecret(48);

// ── Map to infra/.env ───────────────────────────────────────────
const dbHost = "nexo-postgres"; // compose internal network hostname
const dbUrl  = `postgresql://nexo_app:${NEW_DB_PASS}@${dbHost}:5432/nexo?schema=public`;

const entries = [
  "# ── Nexo infrastructure environment ──",
  `# Generated by migrate-env.mjs — ${new Date().toISOString()}`,
  "",
  "# ── Base de datos (contenedor compose) ──",
  `NEXO_DATABASE_URL=${dbUrl}`,
  "",
  "# ── ngrok ──",
  `NGROK_AUTHTOKEN=`,
  "",
  "# ── JWT / Sesiones ──",
  `JWT_SECRET=${NEW_JWT}`,
  `AUTH_SESSION_SECRET=${NEW_AUTH}`,
  `ACCESS_TOKEN_TTL_SECONDS=${env.ACCESS_TOKEN_TTL_SECONDS || "900"}`,
  `REFRESH_TOKEN_TTL_SECONDS=${env.REFRESH_TOKEN_TTL_SECONDS || "604800"}`,
  "",
  "# ── Azure Blob Storage ──",
  `AZURE_STORAGE_CONNECTION_STRING=${env.AZURE_STORAGE_CONNECTION_STRING || ""}`,
  `AZURE_STORAGE_CONTAINER_NAME=${env.AZURE_STORAGE_CONTAINER_NAME || "nexo-photos"}`,
  `AZURE_READ_URL_TTL_SECONDS=${env.AZURE_READ_URL_TTL_SECONDS || "300"}`,
  "",
  "# ── Email (Azure Communication Services) ──",
  `AZURE_COMMUNICATION_CONNECTION_STRING=${env.AZURE_COMMUNICATION_CONNECTION_STRING || ""}`,
  `AZURE_COMMUNICATION_SENDER_ADDRESS=${env.AZURE_COMMUNICATION_SENDER_ADDRESS || ""}`,
  "",
  "# ── Seed users ──",
  `NEXO_SEED_ADMIN_EMAIL=${env.NEXO_SEED_ADMIN_EMAIL || ""}`,
  `NEXO_SEED_ADMIN_PASSWORD=${env.NEXO_SEED_ADMIN_PASSWORD || ""}`,
  `NEXO_SEED_OPERATOR_EMAIL=${env.NEXO_SEED_OPERATOR_EMAIL || ""}`,
  `NEXO_SEED_OPERATOR_PASSWORD=${env.NEXO_SEED_OPERATOR_PASSWORD || ""}`,
  "",
  "# ── Server ──",
  `NODE_ENV=${env.NODE_ENV || "production"}`,
  `PORT=${env.PORT || "3000"}`,
  `LOG_DIR=${env.LOG_DIR || "./logs"}`,
  "",
];

writeFileSync(INFRA_ENV, entries.join("\n") + "\n", "utf8");

// Zero stdout output — values are only in the file.
process.exit(0);
